# Generated by Django 3.1.4 on 2020-12-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la ville')),
            ],
        ),
        migrations.CreateModel(
            name='GarbageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type de déchets')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecttime', models.CharField(blank=True, max_length=100, verbose_name='Heure de collecte')),
                ('openingtime', models.CharField(blank=True, max_length=100, verbose_name="Heure d'ouverture")),
                ('closingtime', models.CharField(blank=True, max_length=100, verbose_name='Heure de fermeture')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.city')),
            ],
        ),
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du déchet')),
                ('garbagetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.garbagetype')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameday', models.CharField(max_length=50, verbose_name='Jour')),
                ('time', models.ManyToManyField(to='search.Time')),
            ],
        ),
        migrations.CreateModel(
            name='CollectLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Lieu de collecte')),
                ('day', models.ManyToManyField(to='search.Day')),
                ('type', models.ManyToManyField(to='search.GarbageType')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.zone')),
            ],
        ),
    ]
