# Generated by Django 3.1.4 on 2020-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Ville', 'verbose_name_plural': 'Villes'},
        ),
        migrations.AlterModelOptions(
            name='collectlocation',
            options={'ordering': ['name'], 'verbose_name': 'Lieu de collecte', 'verbose_name_plural': 'Lieux de collecte'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['nameday'], 'verbose_name': 'Jour', 'verbose_name_plural': 'Jours'},
        ),
        migrations.AlterModelOptions(
            name='garbage',
            options={'ordering': ['name'], 'verbose_name': 'Déchet', 'verbose_name_plural': 'Déchets'},
        ),
        migrations.AlterModelOptions(
            name='garbagetype',
            options={'ordering': ['name'], 'verbose_name': 'Type de déchet', 'verbose_name_plural': 'Types de déchet'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['collecttime'], 'verbose_name': 'Horaire', 'verbose_name_plural': 'Horaires'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AlterField(
            model_name='garbagetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Type de déchet'),
        ),
    ]
