# Generated by Django 3.1.4 on 2020-12-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201203_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='closingtime',
        ),
        migrations.RemoveField(
            model_name='time',
            name='openingtime',
        ),
        migrations.AddField(
            model_name='time',
            name='summertime',
            field=models.CharField(blank=True, max_length=100, verbose_name="Heure d'été'"),
        ),
        migrations.AddField(
            model_name='time',
            name='wintertime',
            field=models.CharField(blank=True, max_length=100, verbose_name="Heure d'hiver"),
        ),
    ]
