# Generated by Django 3.1.4 on 2020-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20201203_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
