# Generated by Django 3.1.4 on 2021-01-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbage',
            name='destination',
            field=models.CharField(default="Poubelle d'ordures ménagères", max_length=60, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='garbage',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
